### ISSUE TITLE
Diagram stopped working

### ISSUE THREAD

**Issue by endeffects** [syncfusion/ej2-blazor-samples#45]
Today i tried to run my application and all samples you have provied and in all versions the diagram does not work anymore. I'm receiving the following error in visual studio:

```
SourceMaps.getMapForGeneratedPath: exception while processing path: https://cdn.syncfusion.com/ej2/dist/ej2.min.js, sourcemap: ej2.min.js.map
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at new SourceMap (C:\ProgramData\Microsoft\VisualStudio\ChromeAdapter\3a3b9ef7\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMap.js:19:25)
    at sourceMapContentsP.then.contents (C:\ProgramData\Microsoft\VisualStudio\ChromeAdapter\3a3b9ef7\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMapFactory.js:54:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by RamyaThiru** [comment]
Hi,

From our beta release(17.2.28), the NuGet package name is changed from Syncfusion.EJ2.AspNet.Core.RazorComponents to Syncfusion.EJ2.Blazor 
So, Please update the NuGet and refer the CDN link for ej2.min.js and ejs.interop.min.js with specific release version. We have provided code example and simple sample for this . Please refer to them as below.

Code example:

Package: namespace
`@using Syncfusion.EJ2.Blazor.Diagrams `

CDN:
`<script src="https://cdn.syncfusion.com/ej2/17.2.29/dist/ej2.min.js"></script> 
 <script src="https://cdn.syncfusion.com/ej2/17.2.29/dist/ejs.interop.min.js"></script>`

Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/diagramSample-1999061229

Please refer to the release notes for package name changes.

Link: https://ej2.syncfusion.com/aspnet-core-blazor/documentation/release-notes/17.2.28/

Regards,
Ramya T

**Comment by endeffects** [comment]
Thank you for your support. Is there any option to subscribe to the release notes?

**Comment by RamyaThiru** [comment]
Hi @endeffects ,

Currently, we don’t have that option. However, you can subscribe to the NuGet package and you can learn the new version update and get the release notes from the NuGet page. 

NuGet feed link - https://www.nuget.org/packages/Syncfusion.EJ2.Blazor/atom.xml

Regards, 
Ramya T
