### ISSUE TITLE
Content Size

### ISSUE THREAD

**Issue by nm-a** [syncfusion/ej2-blazor-samples#54]
Hi Team,
Thank you for the handy demos, there are very useful to start with Syncfusion Blazor Controls. 

When I try to browse these examples, it is downloading huge content (image attached) from the server. Do we have any alternatives to address these size issues?

![image](https://user-images.githubusercontent.com/7089157/62593560-cd746880-b8f4-11e9-9a8e-915aa8356986.png)

thank you
-nm

**Comment by Saranya13** [comment]
Hi @nm-a ,

We would like to let you know that, the online Blazor demos are client-side samples. So, It will download all assemblies while rendering the samples. This was the main reason the increased size of a content. However, currently we are working on converting our sample browser to server side and it will solve this problem. 

Regards,
Saranya M

**Comment by nm-a** [comment]
Thank you @Saranya13, the client side blazor is helpful for the people who wants place ui resources in cdn.

The server side blazor might be good alternative until we get stable solution in blazor client side. 

Thank you
