### ISSUE TITLE
Please update sample to preview 8

### ISSUE THREAD

**Issue by PhilPJL** [syncfusion/ej2-blazor-samples#55]
Could you please update your Blazor Components to Preview 8?

**Comment by honkmother** [comment]
I am going to echo this motion - I know there is work involved here, and that this might not be a high priority since major companies are not using it, but the SyncFusion components are second to none and this is what prevents me from upgrading to P8.

**Comment by Saranya13** [comment]
Hi @PhilPJL ,

We have provided the .Net Core preview 8 support to our blazor components and it included in our latest version 17.2.0.46-beta. Please find the below links.

Github : https://github.com/syncfusion/ej2-blazor-samples

Nuget package: https://www.nuget.org/packages/Syncfusion.EJ2.Blazor/17.2.0.46-beta

Release Notes: https://ej2.syncfusion.com/blazor/documentation/release-notes/17.2.46/

**Note**: There is a break in the @ref functionality in Blazor with Preview 8. If you are accessing our component instance in code behind using @ref, you need to define both @ref and @ref:suppressField in all component’s tag-helper as shown in the below code snippet. Please refer to this GitHub thread for more information.

<EjsGrid @ref="@DefaultGrid" @ref:suppressField >    </EjsGrid>

**Comment by PhilPJL** [comment]
Thanks
